15 update readme language ext webpart
gcxchange-gcechange/spfx-extendlang pull request #16
Opened 2023-09-25 19:19 UTC by RVany

Readme upgraded in new template.

2023-09-29 12:16 UTC, Steph4104 requested changes

2023-09-29 12:31 UTC, RVany commented on README.md
> +Language toggles on Hub sites will be automatically be targeted by this extension. To target sub-sites of a hub site that also has language toggles, change the siteIds values in the extension propert
May I know when it will trigger?

2023-09-29 12:38 UTC, RVany commented on README.md
> +Microsoft Graph - User.ReadBasic.All
I think in onit() method of **_ExtendLanguageApplicationCustomizer.ts_**.  I believe it used to create the url for the language & setting.  We need to direct to profile language setting of the specific user(current user) right?

2023-09-29 13:04 UTC, Steph4104 commented on README.md
> +Language toggles on Hub sites will be automatically be targeted by this extension. To target sub-sites of a hub site that also has language toggles, change the siteIds values in the extension propert
In tour.ts line 282 you can see that its looking for gcxLangTour + the language value

2023-09-29 13:19 UTC, RVany commented on README.md
> +Language toggles on Hub sites will be automatically be targeted by this extension. To target sub-sites of a hub site that also has language toggles, change the siteIds values in the extension propert
Ok. But when and how that url parameter going to trigger.  I thought the registration app redirecting to the url with the parameter gcxLangTour + the language value.

2023-09-29 16:53 UTC, RVany commented on README.md
> +Language toggles on Hub sites will be automatically be targeted by this extension. To target sub-sites of a hub site that also has language toggles, change the siteIds values in the extension propert
I changed the sentence as "When the ***gcxLangTour*** parameter triggers in the URL, a tour about the extension will be displayed." Is it correct?

2023-10-04 17:59 UTC, RVany commented on README.md
> +Language toggles on Hub sites will be automatically be targeted by this extension. To target sub-sites of a hub site that also has language toggles, change the siteIds values in the extension propert
Modified with above text.

2023-10-06 13:27 UTC, Steph4104 approved these changes
Make sure to review what you copy past

2023-10-06 14:54 UTC, merged